name_or_path: /home/nfs02/model/llama-3-8b-instruct
tokenizer_name_or_path: null
archive: null
block_name: LlamaDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: null
reference_dtype: bfloat16
is_lora: true